# Generated by Django 5.1.4 on 2024-12-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='vendor',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='cgst',
            new_name='totalall_gst',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='utilise_credit',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c-l', 'B2C-L'), ('bsc-o', 'BSC-O'), ('nil rated', 'Nil Rated'), ('advance received', 'Advance Received'), ('export', 'Export'), ('unregistered local', 'Unregistered Local'), ('unregistered non-local', 'Unregistered non-Local'), ('sez', 'SEZ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('sales_invoice', 'Sales_Invoice'), ('debit_note', 'Debit Note'), ('income', 'Income')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductSummaryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hsncode')),
                ('prod_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productdescription')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='product_summaries',
            field=models.ManyToManyField(blank=True, related_name='purchase_invoices', to='api.productsummarypurchase'),
        ),
    ]
