# Generated by Django 5.1 on 2024-12-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='utilise_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
