# Generated by Django 5.1.1 on 2024-10-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='attachment',
        ),
        migrations.AddField(
            model_name='files',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bank'),
        ),
    ]
