# Generated by Django 5.1.4 on 2025-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
