# Generated by Django 5.1.4 on 2025-01-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productsummary',
            name='unique_product_in_summary',
        ),
    ]
