# Generated by Django 5.1.4 on 2025-01-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='tds_tcs_rate',
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='tds_tcs_section',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
