# Generated by Django 5.1.1 on 2024-10-18 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='unit_of_measure',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_of_measure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hsncode')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
