# Generated by Django 5.1.4 on 2025-01-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productdescription',
            unique_together=set(),
        ),
    ]
