# Generated by Django 5.1.1 on 2024-09-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='client',
        ),
        migrations.RemoveField(
            model_name='file',
            name='files',
        ),
        migrations.AddField(
            model_name='client',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='files', to='api.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('llp', 'LLP'), ('opc', 'OPC'), ('huf', 'HUF'), ('private ltd', 'Private Ltd'), ('Public Limited', 'public limited'), ('trust', 'Trust')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
