# Generated by Django 5.1.4 on 2025-07-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_others_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipupload',
            name='type_of_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
