# Generated by Django 5.1 on 2024-12-20 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_purchaseinvoice_utilise_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salesinvoice'),
        ),
    ]
