# Generated by Django 5.1.4 on 2025-01-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_salesinvoice_tds_tcs_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='tds_tcs_section',
            new_name='tds_tcs_rate',
        ),
    ]
