# Generated by Django 5.1 on 2025-01-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productdescription_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tcs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
