# Generated by Django 5.1 on 2024-11-06 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productdescription')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductList',
        ),
    ]
