# Generated by Django 5.1.4 on 2025-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_owner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others',
            name='text',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('minute', 'Minute'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
