# Generated by Django 5.1.4 on 2024-12-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_vendor_purchaseinvoice_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='customer',
            new_name='vendor',
        ),
    ]
