# Generated by Django 5.1.4 on 2025-09-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_owner_name_owner_first_name_owner_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='name',
        ),
    ]
