# Generated by Django 5.1.4 on 2025-01-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_tds_tcs_section_salesinvoice_tds_tcs_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='tds_tcs_section',
        ),
        migrations.RemoveField(
            model_name='incomedebitnote',
            name='tds_tcs_section',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='tds_tcs_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomedebitnote',
            name='tds_tcs_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
