# Generated by Django 5.1 on 2024-12-20 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_debitnote_sales_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSummaryCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hsncode')),
                ('prod_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productdescription')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_invoice', models.FileField(blank=True, null=True, upload_to='')),
                ('attach_e_way_bill', models.FileField(blank=True, null=True, upload_to='')),
                ('month', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c-l', 'B2C-L'), ('bsc-o', 'BSC-O'), ('nil rated', 'Nil Rated'), ('advance received', 'Advance Received'), ('export', 'Export'), ('unregistered local', 'Unregistered Local'), ('unregistered non-local', 'Unregistered non-Local'), ('sez', 'SEZ')], max_length=100, null=True)),
                ('entry_type', models.CharField(blank=True, choices=[('sales_invoice', 'Sales_Invoice'), ('debit_note', 'Debit Note'), ('income', 'Income')], max_length=100, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalall_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds_tcs_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds_tcs_section', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tcs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_receivable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilise_edit', models.BooleanField(blank=True, null=True)),
                ('utilise_month', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('client_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officelocation')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.purchaseinvoice')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('product_summaries', models.ManyToManyField(blank=True, related_name='credit_note', to='api.productsummarycreditnote')),
            ],
        ),
    ]
