# Generated by Django 5.1.4 on 2025-09-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_commonuser_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonuser',
            options={},
        ),
        migrations.AddConstraint(
            model_name='commonuser',
            constraint=models.UniqueConstraint(fields=('client', 'email'), name='unique_email_per_client'),
        ),
    ]
