# Generated by Django 5.1.4 on 2025-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_purchaseinvoice_tcs_alter_purchaseinvoice_tds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tcs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
