# Generated by Django 5.1 on 2024-11-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productsummary_delete_productitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsummary',
            old_name='description',
            new_name='prod_description',
        ),
    ]
