# Generated by Django 5.1.4 on 2025-01-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_expenses_tds_tcs_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='tds_tcs_section',
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tds_tcs_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
