# Generated by Django 5.1.4 on 2025-09-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_commonuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdsreturn',
            name='challan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tdsreturn',
            name='last_filed_return_ack_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
