# Generated by Django 5.1 on 2024-11-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_description_productsummary_prod_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officelocation',
            old_name='branch',
            new_name='branchID',
        ),
    ]
