# Generated by Django 5.1.4 on 2025-10-04 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tdsreturn_challan_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
    ]
