# Generated by Django 5.1 on 2024-11-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_branch_officelocation_branchid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officelocation',
            old_name='branchID',
            new_name='branch',
        ),
    ]
