# Generated by Django 5.1.4 on 2025-02-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customer_contact_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(blank=True, choices=[('gstr_1', 'GSTR_1'), ('gstr_3b', 'GSTR_3B'), ('gstr_4', 'GSTR_4'), ('gstr_5', 'GSTR_5'), ('gstr_5a', 'GSTR_5A'), ('gstr', 'GSTR'), ('gstr_7', 'GSTR_7'), ('gstr_8', 'GSTR_8'), ('gstr_9', 'GSTR_9'), ('gstr_10', 'GSTR_10'), ('gstr_11', 'GSTR_11'), ('cmp_8', 'CMP_8'), ('itc_04', 'ITC_04'), ('income_tax', 'Income_Tax'), ('tax_audit', 'Tax_Audit'), ('air', 'AIR'), ('sft', 'SFT'), ('tds_return', 'TDS_Return'), ('tds_payment', 'TDS_Payment'), ('pf', 'PF'), ('esic', 'ESIC'), ('gst_notice', 'GST_Notice'), ('income_tax_notice', 'Income_Tax_Notice')], max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=100, null=True)),
                ('return_period', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('computation', models.FileField(blank=True, null=True, upload_to='')),
                ('client_review', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('return_file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
