# Generated by Django 5.1.4 on 2025-02-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_acknowledgement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='month',
            new_name='po_date',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='po_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
