# Generated by Django 5.1.4 on 2024-12-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_productsummaryexpensescreditnote_expensescreditnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='attach_e_way_bill',
            field=models.FileField(blank=True, null=True, upload_to='e_way_bills/'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='attach_invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
