# Generated by Django 5.1 on 2024-11-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_branchid_officelocation_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='cutomer',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='hsn',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='product_summaries',
            field=models.ManyToManyField(blank=True, related_name='sales_invoices', to='api.productsummary'),
        ),
    ]
