# Generated by Django 5.1.4 on 2024-12-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_debitnote_attach_e_way_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='attach_e_way_bill',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='attach_invoice',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
