# Generated by Django 5.1.4 on 2024-12-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_zipupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipupload',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
