# Generated by Django 5.1 on 2024-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_cutomer_salesinvoice_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
