# Generated by Django 5.1.4 on 2025-03-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_month_salesinvoice_po_date_salesinvoice_po_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acknowledgement',
            old_name='computation',
            new_name='computation_file',
        ),
    ]
