# Generated by Django 5.1 on 2024-11-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_owner_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='status',
            new_name='isadmin',
        ),
    ]
