# Generated by Django 5.1.4 on 2025-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_computation_acknowledgement_computation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgement',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='client_review',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('denied', 'Denied'), ('remark', 'Remark')], max_length=100, null=True),
        ),
    ]
