# Generated by Django 5.1.4 on 2025-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_acknowledgement_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], max_length=100, null=True),
        ),
    ]
