# Generated by Django 5.1 on 2024-11-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_status_owner_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
