# Generated by Django 5.1.4 on 2024-12-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_zipupload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='product_summaries',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='api.productsummaryexpenses'),
        ),
        migrations.AlterField(
            model_name='income',
            name='product_summaries',
            field=models.ManyToManyField(blank=True, related_name='income', to='api.productsummaryincome'),
        ),
    ]
