# Generated by Django 5.1.1 on 2024-11-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_branch_country_branch_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
    ]
