# Generated by Django 5.1.4 on 2025-03-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_acknowledgement_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half_Yearly'), ('yearly', 'Yearly')], max_length=100, null=True),
        ),
    ]
