# Generated by Django 5.1.4 on 2024-12-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_productsummaryexpensescreditnote_expensescreditnote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomedebitnote',
            old_name='imcome',
            new_name='income',
        ),
    ]
