# Generated by Django 5.1.4 on 2025-03-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_acknowledgement_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='client_review',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('to_be_modified', 'To_Be_Modified'), ('remark', 'Remark')], max_length=100, null=True),
        ),
    ]
