# Generated by Django 5.1.4 on 2025-03-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_acknowledgement_client_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acknowledgement',
            name='computation_file',
        ),
        migrations.RemoveField(
            model_name='acknowledgement',
            name='return_file',
        ),
        migrations.AddField(
            model_name='files',
            name='ack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.acknowledgement'),
        ),
        migrations.AddField(
            model_name='files',
            name='computation_file',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='files',
            name='return_file',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
