# Generated by Django 5.1.4 on 2025-03-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_acknowledgement_computation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
