# Generated by Django 5.1.4 on 2025-03-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_owner_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='customer',
        ),
    ]
