# Generated by Django 5.1.4 on 2025-03-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_customuser_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxaudit',
            name='financial_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
