# Generated by Django 5.1.4 on 2025-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_taxaudit_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='financial_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sft',
            name='financial_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
