# Generated by Django 5.1.4 on 2025-03-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_air_financial_year_alter_sft_financial_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
