# Generated by Django 5.1.4 on 2025-03-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tdssection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdspayment',
            name='tds_section',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
