# Generated by Django 5.1.4 on 2025-03-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_tdspayment_tds_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdsreturn',
            name='tds_section',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
