# Generated by Django 5.1.4 on 2025-03-28 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_tdsreturn_tds_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(choices=[('monthly', 'Monthly'), ('minute', 'Minute'), ('other', 'Other')], max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='others',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.others'),
        ),
    ]
