# Generated by Django 5.1.4 on 2025-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_others_files_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitnote',
            old_name='month',
            new_name='po_date',
        ),
        migrations.AddField(
            model_name='debitnote',
            name='po_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
