# Generated by Django 5.1.4 on 2025-04-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_month_debitnote_po_date_debitnote_po_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
