# Generated by Django 5.1.4 on 2025-04-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
    ]
