# Generated by Django 5.1.4 on 2025-04-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdspayment',
            name='tds_challan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tdspayment',
            name='tds_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
