# Generated by Django 5.1.4 on 2025-05-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_tdspayment_tds_challan_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdssection',
            name='client',
        ),
        migrations.AlterField(
            model_name='hsncode',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
