# Generated by Django 5.1.4 on 2025-05-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_tdssection_client_alter_hsncode_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsncode',
            name='hsn_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
